# Generated by Django 4.2.7 on 2024-01-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
