# Generated by Django 4.2.7 on 2024-01-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useraccount_account_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
