# Generated by Django 4.2.7 on 2024-03-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='image',
        ),
    ]
