# Generated by Django 4.2.7 on 2024-01-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
