# Generated by Django 4.2.7 on 2024-01-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookdetails_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='created_on',
        ),
    ]
