# Generated by Django 4.2.7 on 2024-01-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
