# Generated by Django 4.2.7 on 2024-01-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow_book', '0002_borrowbook_borrow_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
